export const ACTION_SUBMIT_ANSWER = 'ACTION_SUBMIT_ANSWER'
export const ACTION_GO_TO_NEXT_QUESTION = 'ACTION_GO_TO_NEXT_QUESTION'
export const ACTION_START_NEW_GAME = 'ACTION_START_NEW_GAME'


export const ACTION_GET_QUESTIONS = 'ACTION_GET_QUESTIONS'
export const ACTION_GET_QUESTIONS_SUCCESS = 'ACTION_GET_QUESTIONS_SUCCESS'
export const ACTION_GET_QUESTIONS_FAILURE = 'ACTION_GET_QUESTIONS_FAILURE'
