export const ACTION_SUBMIT_ANSWER = 'ACTION_SUBMIT_ANSWER'
export const ACTION_GO_TO_NEXT_QUESTION = 'ACTION_GO_TO_NEXT_QUESTION'
export const ACTION_START_NEW_GAME = 'ACTION_START_NEW_GAME'


export const ACTION_GET_NEW_GAME = 'ACTION_GET_NEW_GAME'
export const ACTION_GET_NEW_GAME_SUCCESS = 'ACTION_GET_NEW_GAME_SUCCESS'
export const ACTION_GET_NEW_GAME_FAILURE = 'ACTION_GET_NEW_GAME_FAILURE'


export const ACTION_SUBMIT_SCORE = 'ACTION_SUBMIT_SCORE';
export const ACTION_SUBMIT_SCORE_SUCCESS = 'ACTION_SUBMIT_SCORE_SUCCESS'
export const ACTION_SUBMIT_SCORE_FAILURE = 'ACTION_SUBMIT_SCORE_FAILURE'

export const ACTION_EMIT_NOTIFICATION = 'ACTION_EMIT_NOTIFICATION'


export const ACTION_GO_TO_LATEST_SCORES = 'ACTION_GO_TO_LATEST_SCORES'

export const ACTION_FETCH_LATEST_SCORES = 'ACTION_FETCH_LATEST_SCORES'
export const ACTION_FETCH_LATEST_SCORES_SUCCESS = 'ACTION_FETCH_LATEST_SCORES_SUCCESS'
export const ACTION_FETCH_LATEST_SCORES_FAILURE = 'ACTION_FETCH_LATEST_SCORES_FAILURE'

export const ACTION_TOGGLE_SOUND = 'ACTION_TOGGLE_SOUND'
export const ACTION_PLAY_SOUND = 'ACTION_PLAY_SOUND'
