version: '3'
services:
    web:
      image: docker-tutorial/web
      build:
        context: ./
        dockerfile: deploy/web.dockerfile
      environment:
        - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432
        # Making production the default.
        - QUIZ_ENV=production
    db:
      image: postgres:10.2-alpine
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
